apiVersion: skaffold/v4beta3
kind: Config
metadata:
  name: kiekkotori
build:
  local:
    push: false
  artifacts:
  - image: toukohan/auth
    context: auth
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
  - image: toukohan/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '**/*.js'
          dest: .
  - image: toukohan/products
    context: products
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
  - image: toukohan/orders
    context: orders
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
  - image: toukohan/expiration
    context: expiration
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
  - image: toukohan/payments
    context: payments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
manifests:
  rawYaml:
    - infra/k8s/*
